# -*- coding: utf-8 -*-
"""inventory.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VlGfDCSJCzP4K9k11SeLWYXE3BnheHZy
"""

import pandas as pd

# ==========================================
# 1. ĐỌC DỮ LIỆU
# ==========================================

df = pd.read_csv("/content/inventory.csv")

print("Số dòng ban đầu:", len(df))
print("Số cột:", len(df.columns))


# ==========================================
# 2. XỬ LÝ DỮ LIỆU
# ==========================================

# Xóa dữ liệu trùng
df = df.drop_duplicates()

# Chuyển snapshot_date sang dạng ngày
df["snapshot_date"] = pd.to_datetime(
    df["snapshot_date"],
    errors="coerce"
)

# Chuyển các cột số về dạng số
numeric_columns = [
    "stock_on_hand",
    "units_received",
    "units_sold",
    "stockout_days",
    "days_of_supply",
    "fill_rate",
    "stockout_flag",
    "overstock_flag",
    "reorder_flag",
    "sell_through_rate",
    "year",
    "month"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )

# Xử lý giá trị thiếu
df["stock_on_hand"] = df["stock_on_hand"].fillna(0)
df["units_received"] = df["units_received"].fillna(0)
df["units_sold"] = df["units_sold"].fillna(0)
df["stockout_days"] = df["stockout_days"].fillna(0)

df["days_of_supply"] = df["days_of_supply"].fillna(0)
df["fill_rate"] = df["fill_rate"].fillna(0)
df["sell_through_rate"] = df["sell_through_rate"].fillna(0)

df["stockout_flag"] = df["stockout_flag"].fillna(0)
df["overstock_flag"] = df["overstock_flag"].fillna(0)
df["reorder_flag"] = df["reorder_flag"].fillna(0)

df["product_name"] = df["product_name"].fillna("Unknown")
df["category"] = df["category"].fillna("Unknown")
df["segment"] = df["segment"].fillna("Unknown")


# ==========================================
# 3. CHUẨN HÓA DỮ LIỆU
# ==========================================

text_columns = [
    "product_name",
    "category",
    "segment"
]

for column in text_columns:
    df[column] = df[column].astype(str).str.strip()


# ==========================================
# 4. TỔNG HỢP DỮ LIỆU
# ==========================================

print("\n========== INVENTORY ==========")

print("Số sản phẩm:", df["product_id"].nunique())

print(
    "Tổng tồn kho:",
    df["stock_on_hand"].sum()
)

print(
    "Tổng số lượng nhập:",
    df["units_received"].sum()
)

print(
    "Tổng số lượng bán:",
    df["units_sold"].sum()
)

print(
    "Tổng số ngày hết hàng:",
    df["stockout_days"].sum()
)


# ==========================================
# 5. TỔNG HỢP THEO CATEGORY
# ==========================================

category_summary = df.groupby("category").agg(
    total_stock=("stock_on_hand", "sum"),
    total_received=("units_received", "sum"),
    total_sold=("units_sold", "sum"),
    total_stockout_days=("stockout_days", "sum")
).reset_index()

print("\n========== THEO CATEGORY ==========")
print(category_summary)


# ==========================================
# 6. TỔNG HỢP THEO SẢN PHẨM
# ==========================================

product_summary = df.groupby(
    ["product_id", "product_name"]
).agg(
    total_stock=("stock_on_hand", "sum"),
    total_received=("units_received", "sum"),
    total_sold=("units_sold", "sum"),
    total_stockout_days=("stockout_days", "sum")
).reset_index()


# ==========================================
# 7. XUẤT DỮ LIỆU
# ==========================================

df.to_csv(
    "/content/inventory_processed.csv",
    index=False
)

category_summary.to_csv(
    "/content/inventory_category_summary.csv",
    index=False
)

product_summary.to_csv(
    "/content/inventory_product_summary.csv",
    index=False
)

print("\nĐã xử lý xong Inventory!")
print("Đã tạo inventory_processed.csv")
print("Đã tạo inventory_category_summary.csv")
print("Đã tạo inventory_product_summary.csv")