# -*- coding: utf-8 -*-
"""order_items.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7ut5ZWyCX6EsKoxLy10XDLm7TSGMN8r
"""

import pandas as pd

# ==========================================
# 1. ĐỌC DỮ LIỆU
# ==========================================

df = pd.read_csv("/content/order_items.csv", low_memory=False)

print("Số dòng ban đầu:", len(df))
df.head(5)


# ==========================================
# 2. XỬ LÝ DỮ LIỆU
# ==========================================

# Xóa các dòng bị trùng
df = df.drop_duplicates()

# Xử lý giá trị thiếu ở các cột số
df["quantity"] = df["quantity"].fillna(0)
df["unit_price"] = df["unit_price"].fillna(0)
df["discount_amount"] = df["discount_amount"].fillna(0)

# Đảm bảo kiểu dữ liệu
df["order_id"] = df["order_id"].astype(int)
df["product_id"] = df["product_id"].astype(int)
df["quantity"] = df["quantity"].astype(int)

# Chuyển các cột giá về số
df["unit_price"] = pd.to_numeric(df["unit_price"], errors="coerce").fillna(0)
df["discount_amount"] = pd.to_numeric(
    df["discount_amount"], errors="coerce"
).fillna(0)


# ==========================================
# 3. TÍNH TOÁN DỮ LIỆU
# ==========================================

# Thành tiền trước giảm giá
df["total_price"] = df["quantity"] * df["unit_price"]

# Thành tiền sau giảm giá
df["final_price"] = df["total_price"] - df["discount_amount"]


# ==========================================
# 4. TỔNG HỢP DỮ LIỆU
# ==========================================

total_orders = df["order_id"].nunique()
total_products = df["product_id"].nunique()
total_quantity = df["quantity"].sum()
total_revenue = df["total_price"].sum()
total_discount = df["discount_amount"].sum()
final_revenue = df["final_price"].sum()


# ==========================================
# 5. IN KẾT QUẢ
# ==========================================

print("\n===== ORDER ITEMS =====")

print("Tổng số đơn hàng:", total_orders)
print("Tổng số sản phẩm:", total_products)
print("Tổng số lượng sản phẩm:", total_quantity)
print("Tổng doanh thu trước giảm:", total_revenue)
print("Tổng tiền giảm giá:", total_discount)
print("Tổng doanh thu sau giảm:", final_revenue)


df.to_csv("/content/order_items.csv", index=False)