# -*- coding: utf-8 -*-
"""orders.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yB_9BlsF6CAC13F4ToJt-FXZA6dC5L65
"""

import pandas as pd

# ============================================
# 1. ĐỌC DỮ LIỆU
# ============================================

df = pd.read_csv("/content/orders_enriched.csv")

print("Số dòng ban đầu:", len(df))
print("Số cột:", len(df.columns))
print("Tên các cột trong DataFrame:", df.columns.tolist())


# ============================================
# 2. XỬ LÝ DỮ LIỆU
# ============================================

# Xóa các dòng bị trùng
df = df.drop_duplicates()

# Chuyển order_date về dạng ngày
df["order_date"] = pd.to_datetime(
    df["order_date"],
    errors="coerce"
)

# Chuyển years_experience về số (Sửa từ 'years_exp')
if 'years_experience' in df.columns:
    df["years_experience"] = pd.to_numeric(
        df["years_experience"],
        errors="coerce"
    )
else:
    print("Cảnh báo: Cột 'years_experience' không tồn tại trong DataFrame. Bỏ qua xử lý cột này.")

# Xử lý giá trị thiếu
# Sửa từ 'zip_code' thành 'zip'
if 'zip' in df.columns:
    df["zip"] = df["zip"].fillna(0)
else:
    print("Cảnh báo: Cột 'zip' không tồn tại trong DataFrame. Bỏ qua xử lý cột này.")

df["city"] = df["city"].fillna("Unknown")
df["region"] = df["region"].fillna("Unknown")
df["district"] = df["district"].fillna("Unknown")

df["order_status"] = df["order_status"].fillna("Unknown")
df["payment_method"] = df["payment_method"].fillna("Unknown")
df["device_type"] = df["device_type"].fillna("Unknown")
df["order_source"] = df["order_source"].fillna("Unknown")

# Sửa từ 'sales_emp_id' thành 'sales_employee_id'
if 'sales_employee_id' in df.columns:
    df["sales_employee_id"] = df["sales_employee_id"].fillna("Unknown")
else:
    print("Cảnh báo: Cột 'sales_employee_id' không tồn tại trong DataFrame. Bỏ qua xử lý cột này.")

# Sửa từ 'sales_emp_name' thành 'sales_employee_name'
if 'sales_employee_name' in df.columns:
    df["sales_employee_name"] = df["sales_employee_name"].fillna("Unknown")
else:
    print("Cảnh báo: Cột 'sales_employee_name' không tồn tại trong DataFrame. Bỏ qua xử lý cột này.")

df["marital_status"] = df["marital_status"].fillna("Unknown")

# Sửa từ 'education' thành 'education_level'
if 'education_level' in df.columns:
    df["education_level"] = df["education_level"].fillna("Unknown")
else:
    print("Cảnh báo: Cột 'education_level' không tồn tại trong DataFrame. Bỏ qua xử lý cột này.")

df["comment"] = df["comment"].fillna("No comment")


# ============================================
# 3. CHUẨN HÓA DỮ LIỆU TEXT
# ============================================

text_columns = [
    "city",
    "region",
    "district",
    "order_status",
    "payment_method",
    "device_type",
    "order_source",
    "sales_employee_name", # Sửa từ 'sales_emp_name'
    "marital_status",
    "education_level" # Sửa từ 'education'
]

for column in text_columns:
    if column in df.columns: # Thêm kiểm tra cột tồn tại trước khi xử lý
        df[column] = df[column].astype(str).str.strip()
    else:
        print(f"Cảnh báo: Cột '{column}' không tồn tại trong DataFrame. Bỏ qua chuẩn hóa cột này.")


# ============================================
# 4. TỔNG HỢP DỮ LIỆU
# ============================================

print("\n========== TỔNG HỢP ORDERS ENRICHED ==========")

# Check if columns exist before using .nunique() or .value_counts()
if 'order_id' in df.columns: print("Tổng số đơn hàng:", df["order_id"].nunique())
else: print("Tổng số đơn hàng: Không có cột 'order_id'")

if 'customer_id' in df.columns: print("Tổng số khách hàng:", df["customer_id"].nunique())
else: print("Tổng số khách hàng: Không có cột 'customer_id'")

# Sửa từ 'sales_emp_id' thành 'sales_employee_id'
if 'sales_employee_id' in df.columns: print("Tổng số nhân viên:", df["sales_employee_id"].nunique())
else: print("Tổng số nhân viên: Không có cột 'sales_employee_id'")

print("\nSố đơn theo trạng thái:")
if 'order_status' in df.columns: print(df["order_status"].value_counts())
else: print("Không có cột 'order_status'")

print("\nSố đơn theo phương thức thanh toán:")
if 'payment_method' in df.columns: print(df["payment_method"].value_counts())
else: print("Không có cột 'payment_method'")

print("\nSố đơn theo thiết bị:")
if 'device_type' in df.columns: print(df["device_type"].value_counts())
else: print("Không có cột 'device_type'")

print("\nSố đơn theo nguồn đơn hàng:")
if 'order_source' in df.columns: print(df["order_source"].value_counts())
else: print("Không có cột 'order_source'")


# ============================================
# 5. ĐƯA DỮ LIỆU VÀO TABLE
# ============================================

df.to_csv(
    "/content/orders_enriched_processed.csv",
    index=False
)

print("\nĐã xử lý xong!")
print("File kết quả: orders_enriched_processed.csv")
print("Số dòng sau khi xử lý:", len(df))