# -*- coding: utf-8 -*-
"""shipper_silver.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PHO0qnFlb62ni4TfrNBp4Tbt3382eL2Q
"""

import pandas as pd

# ==========================================
# 1. ĐỌC DỮ LIỆU
# ==========================================

df = pd.read_csv("/content/shipments_realistic.csv")

print("Số dòng ban đầu:", len(df))
print("Số cột:", len(df.columns))


# ==========================================
# 2. XỬ LÝ DỮ LIỆU
# ==========================================

# Xóa các dòng bị trùng
df = df.drop_duplicates()

# Chuyển các cột ngày sang dạng datetime
df["ship_date"] = pd.to_datetime(
    df["ship_date"],
    errors="coerce"
)

df["delivery_date"] = pd.to_datetime(
    df["delivery_date"],
    errors="coerce"
)

df["join_date"] = pd.to_datetime(
    df["join_date"],
    errors="coerce"
)


# Chuyển các cột số về dạng numeric
numeric_columns = [
    "shipping_fee",
    "shipper_experience_years",
    "shipper_rating",
    "delivery_success_rate",
    "average_delivery_time",
    "shipper_age"
]

for column in numeric_columns:
    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )


# ==========================================
# 3. XỬ LÝ GIÁ TRỊ THIẾU
# ==========================================

df["shipping_fee"] = df["shipping_fee"].fillna(0)
df["shipper_experience_years"] = df[
    "shipper_experience_years"
].fillna(0)

df["shipper_rating"] = df["shipper_rating"].fillna(
    df["shipper_rating"].mean()
)

df["delivery_success_rate"] = df[
    "delivery_success_rate"
].fillna(
    df["delivery_success_rate"].mean()
)

df["average_delivery_time"] = df[
    "average_delivery_time"
].fillna(
    df["average_delivery_time"].mean()
)


# ==========================================
# 4. TÍNH THỜI GIAN GIAO HÀNG
# ==========================================

df["delivery_days"] = (
    df["delivery_date"] - df["ship_date"]
).dt.days


# ==========================================
# 5. CHUẨN HÓA DỮ LIỆU TEXT
# ==========================================

text_columns = [
    "shipper_company",
    "shipper_vehicle",
    "working_shift",
    "shipper_name",
    "shipper_gender",
    "shipper_marital_status",
    "shipper_education",
    "city",
    "region",
    "district"
]

for column in text_columns:
    df[column] = df[column].fillna("Unknown")
    df[column] = df[column].astype(str).str.strip()


# ==========================================
# 6. TỔNG HỢP DỮ LIỆU
# ==========================================

print("\n========== SHIPMENTS ==========")

print(
    "Tổng số đơn hàng:",
    df["order_id"].nunique()
)

print(
    "Tổng số shipper:",
    df["shipper_id"].nunique()
)

print(
    "Tổng phí vận chuyển:",
    df["shipping_fee"].sum()
)

print(
    "Thời gian giao hàng trung bình:",
    df["delivery_days"].mean()
)


# ==========================================
# 7. TỔNG HỢP THEO CÔNG TY VẬN CHUYỂN
# ==========================================

company_summary = df.groupby(
    "shipper_company"
).agg(
    total_shipments=("order_id", "count"),
    total_shipping_fee=("shipping_fee", "sum"),
    average_rating=("shipper_rating", "mean"),
    average_delivery_time=("delivery_days", "mean")
).reset_index()

print("\n========== THEO CÔNG TY ==========")
print(company_summary)


# ==========================================
# 8. XUẤT TABLE SHIPMENTS
# ==========================================

df.to_csv(
    "/content/shipments_processed.csv",
    index=False
)

print("\nĐã xử lý xong table Shipments!")
print("File kết quả: shipments_processed.csv")